a = int(input("Digite o primeiro número: "))
b = int(input("Digite o segundo número: "))
print(a, " + ", b, " = ", a + b)
print(a, " - ", b, " = ", a - b)
print(a, " * ", b, " = ", a * b)
print(a, " / ", b, " = ", a / b)